language: java
python:
  - "2.7"
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - python-pip
      - python-virtualenv
      - oracle-java8-installer
      - build-essential
      - wget
      - mercurial

# Use Trusty to get enough RAM
sudo: required
dist: trusty

env:
  global:
    - DEFAULT_VM="jvmci"
before_install:
  - virtualenv venv
  - source venv/bin/activate
  - pip install astroid==1.1.0
  - pip install pylint==1.1.0
install:
  - export MX_PATH=$TRAVIS_BUILD_DIR/../mx
  - git clone https://github.com/graalvm/mx.git $MX_PATH
  - export PATH=$MX_PATH/../mx:$PATH
  - export JDT=$MX_PATH/ecj.jar
  - wget http://ftp.halifax.rwth-aachen.de/eclipse//eclipse/downloads/drops4/R-4.5.1-201509040015/ecj-4.5.1.jar -O $JDT
  - export ECLIPSE_TAR=$TRAVIS_BUILD_DIR/../eclipse.tar.gz
  - wget https://lafo.ssw.uni-linz.ac.at/slavefiles/gate/eclipse-jdk8-linux-x86_64.tar.gz -O $ECLIPSE_TAR
  - tar -C $TRAVIS_BUILD_DIR/.. -xf $ECLIPSE_TAR
  - export ECLIPSE_EXE=$TRAVIS_BUILD_DIR/../eclipse/eclipse
  - export MX_BINARY_SUITES=jvmci,truffle
script:
  - mx --strict-compliance gate --strict-mode --simple
after_failure:
  - cat hs_err*
