language: java
python:
  - "2.7"
addons:
  apt:
    packages:
      - python-pip
      - python-virtualenv
      - wget
      - mercurial

# Use Trusty to get enough RAM
sudo: required
dist: trusty

env:
  global:
    - MX_BINARY_SUITES="truffle"
    - JVMCI_VERSION="jvmci-0.21"
  matrix:
    - JDK="jdk8" GATE="style,fullbuild"
    - JDK="jdk8" GATE="build,test"
    - JDK="jdk8" GATE="build,bootstraplite"
#    - JDK="jdk9" GATE="build,test"
#    - JDK="jdk9" GATE="build,bootstraplite"
install:
  - |
      export MX_PATH=$TRAVIS_BUILD_DIR/../mx
      git clone https://github.com/graalvm/mx.git $MX_PATH
      export PATH=$PATH:$MX_PATH
  - |
      if [[ $GATE == *style* ]]
      then
        virtualenv venv
        source venv/bin/activate
        pip install astroid==1.1.0
        pip install pylint==1.1.0

        export ECLIPSE_TAR=$TRAVIS_BUILD_DIR/../eclipse.tar.gz
        wget http://lafo.ssw.uni-linz.ac.at/sulong-deps/eclipse-jdk8-linux-x86_64.tar.gz -O $ECLIPSE_TAR
        tar -C $TRAVIS_BUILD_DIR/.. -xf $ECLIPSE_TAR
        export ECLIPSE_EXE=$TRAVIS_BUILD_DIR/../eclipse/eclipse
      fi
  - |
      if [[ $GATE == *fullbuild* ]]
      then
        export JDT=$MX_PATH/ecj.jar
        wget http://archive.eclipse.org/eclipse/downloads/drops4/R-4.5.2-201602121500/ecj-4.5.2.jar -O $JDT
      fi
  - |
      if [ "$JDK" == "jdk8" ]
      then
        JDK_TAR=$TRAVIS_BUILD_DIR/../jdk1.8.0_91-$JVMCI_VERSION-linux-amd64.tar.gz
        wget https://github.com/dougxc/openjdk8-jvmci-builder/releases/download/$JVMCI_VERSION/jdk1.8.0_91-$JVMCI_VERSION-linux-amd64.tar.gz -O $JDK_TAR
        tar -C $TRAVIS_BUILD_DIR/.. -xzf $JDK_TAR
        export JAVA_HOME=$TRAVIS_BUILD_DIR/../jdk1.8.0_91-$JVMCI_VERSION
      fi
  - |
      if [ "$JDK" == "jdk9" ]
      then
        JDK_TAR=$TRAVIS_BUILD_DIR/../jdk9-SNAPSHOT-release-linux-amd64.tar.gz
        wget https://lafo.ssw.uni-linz.ac.at/slavefiles/jdk/jdk9-SNAPSHOT-release-linux-amd64.tar.gz -O $JDK_TAR
        tar -C $TRAVIS_BUILD_DIR/.. -xf $JDK_TAR
        export JAVA_HOME=$TRAVIS_BUILD_DIR/../jdk1.9.0
      fi
script:
  - mx --strict-compliance gate --strict-mode --tags $GATE
after_failure:
  - cat hs_err*
